# Generated by Django 3.1.4 on 2020-12-28 06:49

from django.db import migrations
from django.core.management import call_command

def load_fixtures(apps, schema_editor):
    for fixture_name in ['Game', 'User']:
        call_command("loaddata", fixture_name)

def rollback(apps, schema_editor):
    for model_name in ["Game", 'User']:
        model = apps.get_model("yourapp", model_name)
        model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('mUtomik', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, rollback),
    ]
