# Generated by Django 3.1.4 on 2020-12-28 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mUtomik', '0002_auto_20201228_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playsession',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
