# Generated by Django 3.1.4 on 2020-12-28 20:42

import Utomik.mUtomik.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mUtomik', '0005_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='file',
            field=models.FileField(upload_to='', validators=[Utomik.mUtomik.validators.validate_file_extension]),
        ),
    ]
