# Generated by Django 3.1.4 on 2020-12-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201227_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_played',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.game'),
        ),
    ]
